name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache playwright
        uses: actions/cache@v5
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1.57.0

      - name: Install dependencies
        run: bun install

      - name: Install playwright
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: bunx playwright install --with-deps --only-shell

      - name: Build
        run: bun run build

      - name: Check types
        run: bun run check:types

      - name: Check lint rules
        run: bun run check:rules

      - name: Check formatting
        run: bun run check:format

      - name: Run tests
        run: bun run test
